version: "2.3"
services:
  node:
    image: node:14.15.1-alpine
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - $PWD:/home/node
      - /etc/localtime:/etc/localtime:ro
    user: node
    working_dir: /home/node
    restart: "no"
    network_mode: bridge
    links:
      - mysql
    tty: false
    #    entrypoint: |
    #      ./scripts/wait-for-it -wait tcp://${PG_HOST:-10.102.0.3}:${PG_PORT:-5432} -wait-retry-interval 5s -timeout 600s
    command: "sh -c 'npm install && npm run nodemon'"

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shortener
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: "no"
    network_mode: bridge

volumes:
  mysql-storage:
    driver: local
