version: "2.3"
services:
  node:
    image: node:14.15.1-alpine
    expose:
      - 3000
    ports:
      - ${HTTP_PORT:-3000}:3000
    volumes:
      - $PWD:/home/node
      - /etc/localtime:/etc/localtime:ro
    user: node
    working_dir: /home/node
    restart: "always"
    networks:
      main: { }
    tty: false
    command: "sh -c 'npm install --only prod; npm start'"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shortener
    volumes:
      - mysql-storage:/var/lib/mysql
    restart: "always"
    networks:
      main: { }

volumes:
  mysql-storage:
    driver: local

networks:
  main:
